name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Just
      uses: extractions/setup-just@v1
      with:
        just-version: '1.14.0'
    
    - name: Install dependencies
      run: just install
    
    - name: Format code
      run: just format

    - name: Run tests
      run: just test

